TRANSCRIBE = "TRANSCRIBE"
SEGMENT = "SEGMENT"
CAPTION = "CAPTION"
UTILITY_PING = "UTILITY_PING"
UTILITY_ECHO = "UTILITY_ECHO"

ALL_TASK_TYPES = {
    TRANSCRIBE,
    SEGMENT,
    CAPTION,
    UTILITY_PING,
    UTILITY_ECHO,
}
